app/Http/Controllers/Auth/RegisteredUserController.php, resources/views/auth/register.blade.php
aggiunto cognome al form di registrazione
=> added surname to register form

app/Http/Controllers/Auth/RegisteredUserController.php, resources/views/auth/register.blade.php
added birth date to registration form
=> added birth date to registration form

app/Models/Apartment.php, resources/views/admin/apartments/index.blade.php, resources/views/layouts/app.blade.php
=> created admin apartment index

app/Http/Controllers/Admin/ApartmentController.php, app/Models/Apartment.php, database/migrations/2024_04_17_142434_create_apartments_table.php, resources/views/admin/apartments/create.blade.php, resources/views/includes/form.blade.php, resources/views/layouts/app.blade.php
created form and fix controller
=> created form and fix controller

app/Http/Controllers/Admin/ApartmentController.php, resources/views/admin/apartments/trash.blade.php, routes/web.php
=> fixed soft deletes

app/Http/Controllers/Admin/ApartmentController.php, app/Models/Apartment.php, resources/scss/index.scss, resources/views/includes/form.blade.php
added tomtom api call to adress input + db store
=> 21 implement tom tom api in form

app/Models/Apartment.php, resources/scss/index.scss, resources/views/admin/apartments/index.blade.php, resources/views/includes/form.blade.php
- added cover image to index
- changed toggle is_visible style in index and form views
- changed services index style
- changed info button style
=> index and form style change

database/seeders/ApartmentSeeder.php, resources/scss/index.scss, resources/views/admin/apartments/index.blade.php
33 add cover image in admin index
=> 33 add cover image in admin index

resources/js/delete_confirmation.js, resources/views/admin/apartments/index.blade.php, resources/views/admin/apartments/trash.blade.php
Added modal in apartments index
=> 37 modal apartment index

resources/views/admin/apartments/trash.blade.php, resources/views/includes/alerts.blade.php, resources/views/layouts/app.blade.php
=> 43 add alerts

app/Http/Controllers/Admin/ApartmentController.php, resources/views/includes/form.blade.php
=> fixed form checkbox

app/Http/Controllers/Admin/HomeController.php, resources/views/admin/home.blade.php
=> changed admin dashboard

resources/views/includes/navbar.blade.php
changed admin home to dashboard label
=> changed admin home to dashboard label

resources/scss/app.scss, resources/scss/dashboard.scss, resources/views/admin/apartments/trash.blade.php, resources/views/admin/home.blade.php
added dashboard style and changed trash icon to come back
=> added dashboard style and changed trash icon to come back

resources/views/auth/register.blade.php
changed registration form color
=> changed registration form color

app/Http/Controllers/Auth/RegisteredUserController.php, resources/views/auth/register.blade.php
=> 69 fix registration form

resources/views/admin/apartments/trash.blade.php
=> changed trash style

app/Http/Requests/Apartment/StoreApartmentRequest.php, resources/views/includes/form.blade.php
=> fixed address validation

app/Http/Requests/Apartment/StoreApartmentRequest.php, app/Http/Requests/Apartment/UpdateApartmentRequest.php, resources/views/includes/form.blade.php
=> Form validation

resources/views/admin/apartments/trash.blade.php
=> fixed trash page

app/Http/Controllers/Auth/RegisteredUserController.php
added validation on birth of date in registration form
=> added validation on birth of date in registration form

resources/views/admin/apartments/trash.blade.php
=> fixed trash

app/Http/Controllers/Auth/RegisteredUserController.php
added email e password validation
=> added email e password validation

app/Http/Controllers/Api/ApartmentController.php, resources/views/includes/form.blade.php, routes/api.php
implemented api to manage the apartment search
=> 94 implement api to manage the apartment search

app/Models/Apartment.php
added image function and and public $with for services
=> 95 image public function

app/Http/Controllers/Api/ApartmentController.php, app/Http/Controllers/Api/ServiceController.php, routes/api.php
=> 105 advanced search filter

app/Http/Controllers/MessageController.php
=> added validations

app/Http/Controllers/Admin/ApartmentController.php, resources/views/admin/apartments/index.blade.php, resources/views/admin/apartments/statistics.blade.php, routes/web.php
added bar chart with views and messages DB data in statistics page
=> added bar chart in statistics page

resources/scss/index.scss, resources/views/admin/apartments/index.blade.php
=> added index media query

database/seeders/ServiceSeeder.php, resources/scss/payments.scss, resources/views/admin/home.blade.php, resources/views/includes/form.blade.php
=> fixed responsive layout

app/Http/Controllers/Admin/SponsorshipController.php, resources/js/sponsorship_page.js, resources/scss/payments.scss, resources/views/admin/apartments/payment-confirmation.blade.php, resources/views/admin/apartments/sponsorship.blade.php
added payment confirmation page
=> 140 sponsorship
